# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

# python, os, and env generate the test matrix
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly

os:
  - linux

env:
  - NP_CONSTRAINT=requirements/constraint_np111.txt
  - NP_CONSTRAINT=requirements/constraint_np112.txt
  
# test matrix modifications
matrix:
  # add OSX jobs to matrix
  include:
    # latest Python 2.7.X
    - language: generic
      python: 2.7
      os: osx
      env: NP_CONSTRAINT=requirements/constraint_np112.txt
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
        - python --version
    # latest Python 3.X
    - language: generic
      python: 2.7
      os: osx
      env: NP_CONSTRAINT=requirements/constraint_np112.txt
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - python --version
  # allowed job failures that will not fail the entire build
  allow_failures:
    - python: nightly

before_install:
  - python --version

install:
  - pip install --upgrade pip
  - pip install --ignore-installed -c $NP_CONSTRAINT -r requirements/requirements_dev.txt
  - pip list

script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
