# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
  
env:
  - NUMPY_VERSION=1.11
  - NUMPY_VERSION=1.12
  
matrix:
  exclude:
    - python: 2.6
      env: NUMPY_VERSION=1.12
  allow_failures:
    - python: nightly

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install numpy==$NUMPY_VERSION
  - pip install -r requirements_dev.txt

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
