# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

# python and env generate the test matrix
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly

os:
  - linux
  - osx

env:
  - NP_CONSTRAINT=requirements/constraint_np111.txt
  - NP_CONSTRAINT=requirements/constraint_np112.txt
  
# test matrix modifications
matrix:
  allow_failures:
    # allow failures for old and new Python versions
    - python: nightly

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install --ignore-installed -c $NP_CONSTRAINT -r requirements/requirements_dev.txt
  - pip list

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
