os: linux
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly
env:
  - NP_VER="1.11.*"
  - NP_VER="1.12.*"
  
matrix:
  # add OSX jobs to matrix
  include:
    # latest Python 2.7.X
    - language: generic
      python: 2.7
      os: osx
      env: NP_VER="1.12.*"
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
        - python --version
    # latest Python 3.X
    - language: generic
      python: 2.7
      os: osx
      env: NP_VER="1.12.*"
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - python --version
  # allowed job failures that will not fail the entire build
  allow_failures:
    - python: nightly

before_install:
  - python --version

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements/requirements-dev.txt
  - pip install numpy==${NP_VER}
  - pip list

script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
