# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

# python and env generate the test matrix
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly
  
env:
  - NUMPY_CONSTRAINT=constraint_np110.txt
  - NUMPY_CONSTRAINT=constraint_np111.txt
  - NUMPY_CONSTRAINT=constraint_np112.txt
  
# test matrix modifications
matrix:
  exclude:
    - python: 2.6
      env: NUMPY_CONSTRAINT=constraint_np112.txt
  allow_failures:
    - python: nightly

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install --ignore-installed -c $NUMPY_CONSTRAINT -r requirements_dev.txt
  - pip list

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
