# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

# python and env generate the test matrix
python:
  - 2.7
  - 3.5
  - 3.6
  - nightly

os:
  - linux

env:
  - NP_CONSTRAINT=requirements/constraint_np111.txt
  - NP_CONSTRAINT=requirements/constraint_np112.txt
  
# test matrix modifications
matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
      env: NP_CONSTRAINT=requirements/constraint_np112.txt
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
    - language: generic
      python: 2.7
      os: osx
      env: NP_CONSTRAINT=requirements/constraint_np112.txt
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
  allow_failures:
    # allow failures for old and new Python versions
    - python: nightly

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - python --version
  - pip install --upgrade pip
  - pip install --ignore-installed -c $NP_CONSTRAINT -r requirements/requirements_dev.txt
  - pip list

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make coverage

after_success:
  - codeclimate-test-reporter
