
os: linux
language: python

matrix:
  include:
    
    # Linux jobs
    - python: 2.7
      env: TOX_ENV=py27-np111
    - python: 2.7
      env: TOX_ENV=py27-np112
    - python: 3.6
      env: TOX_ENV=py36-np111
    - python: 3.6
      env: TOX_ENV=py36-np112
    - python: 2.7
      env: TOX_ENV=code_quality
    
    # OSX jobs
    # Python 2.7.X
    - language: generic
      python: 2.7
      os: osx
      env: TOX_ENV=py27-np112
      before_install:
        - virtualenv env -p python
        - source env/bin/activate
        - python --version
    # Python 3.X
    - language: generic
      python: 2.7
      os: osx
      env: TOX_ENV=py36-np112
      before_install:
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - python --version

before_install:
  - python --version

install:
  - pip install --upgrade pip
  - pip install tox codeclimate-test-reporter

script:
  - tox -e "${TOX_ENV}"

after_success:
  - codeclimate-test-reporter
